# Generated by Django 3.2.23 on 2024-01-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_ingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Recipes',
        ),
    ]
